"""resetTokens on user

Revision ID: 924aaf7671d6
Revises: a382b725503e
Create Date: 2020-07-29 19:38:03.543725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924aaf7671d6'
down_revision = 'a382b725503e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resetToken', sa.String(), nullable=True))
    op.add_column('users', sa.Column('resetTokenExpiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resetTokenExpiry')
    op.drop_column('users', 'resetToken')
    # ### end Alembic commands ###
