"""post can null author

Revision ID: a382b725503e
Revises: ea0497da6c17
Create Date: 2020-07-03 18:27:08.658312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a382b725503e'
down_revision = 'ea0497da6c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'postAuthor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'postAuthor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
